package edu.temple.dicethrow

import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.TextView
import androidx.lifecycle.ViewModelProvider
import kotlin.random.Random

// A key to retrieve the number of sides of the die
const val DIESIDE = "sidenumber"

class DieFragment : Fragment() {
    //Initialize ViewModel
//    lateinit var dieViewModel: DieViewModel
    //Alternative way to initialize ViewModel
    val dieViewModel: DieViewModel by lazy {
        ViewModelProvider(requireActivity())[DieViewModel::class.java]
    }

    //Initializing the TextView
    lateinit var dieTextView: TextView

    // A default value for the sides of the die
    var dieSides: Int = 6

    // Sets up the DieFragment class AKA the constructor
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        //Initialize the ViewModel
        //dieViewModel = ViewModelProvider(requireActivity())[DieViewModel::class.java]

        //So when a DieFragment is created, check if there are any arguments and that it passes
        // a bundle. In this bundle, it will get the integer value of the die sides
        // Set the dieSide variable we have with the value in the bundle
        arguments?.let {
            it.getInt(DIESIDE).run {
                dieSides = this
            }
        }
    }


    // Initialize our view. In this case, we have a single TextView that will display the number
    // Here, it is inflated and defined
    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_die, container, false).apply {
            //Initialize the TextView in the layout
            dieTextView = findViewById(R.id.dieTextView)
        }
    }


    // When the view is created, a number is randomly generated by calling our function
    // throwDie(). Additionally, when the TextView is clicked, the number will randomize again
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        dieViewModel.getRollValue().observe(requireActivity()) {
            //When the rollValue is not 0, display the rollValue
            dieTextView.text = it.toString()
        }

        if (dieViewModel.getRollValue().value == null ) {
            throwDie()
        }
    }

    // A simple random number generator that generates a number from 1 to the number of sides
    fun throwDie() {
        //Random.nextInt(dieSide) generates a number from 0-5
        //Adding 1 to the result will generate a number from 1-6
        //Save the roll value in a LiveData object. This value can be observed by any activity
        dieViewModel.setRollValue(Random.nextInt(dieSides) + 1)
    }

    // A companion object that creates a new instance of the DieFragment class,
    // Quick way to access our DieFragment constructor
    companion object {
        //Creating function newInstance, which will create a DieFragment object
        fun newInstance(sides: Int): DieFragment {
            //Create a bundle to pass the number of sides
            val bundle = Bundle()
            bundle.putInt(DIESIDE, sides)

            //Create die fragment object
            val frag = DieFragment()

            //Put bundle in the fragment
            frag.arguments = bundle

            //return the DieFragment
            return frag
        }
    }
}